### PR TITLE
feat: produce debian package

### PR DESCRIPTION
**Pull request by JonathanWilbur**
This PR is only for Meerkat DSA. I plan to do this for the X.500 CLI separately.

### CODE REVIEW

**Comment by JonathanWilbur** [comment]
Current status: this builds and installs, but it fails to startup.

```text
Dec 25 16:12:35 REDACTED sh[923486]: file:///usr/lib/meerkat/node_modules/@jsr/std__encoding/base64.js:73
Dec 25 16:12:35 REDACTED sh[923486]:   return new Uint8Array(output.buffer.transfer(decode(output, 0, 0, rAlphabet, padding)));
Dec 25 16:12:35 REDACTED sh[923486]:                                       ^
Dec 25 16:12:35 REDACTED sh[923486]: TypeError: output.buffer.transfer is not a function
Dec 25 16:12:35 REDACTED sh[923486]:     at decodeBase64 (file:///usr/lib/meerkat/node_modules/@jsr/std__encoding/base64.js:73:39)
Dec 25 16:12:35 REDACTED sh[923486]:     at new PEMObject (file:///usr/lib/meerkat/node_modules/@wildboar/pem/source/index.js:105:21)
Dec 25 16:12:35 REDACTED sh[923486]:     at PEMObject.parse (file:///usr/lib/meerkat/node_modules/@wildboar/pem/source/index.js:58:20)
Dec 25 16:12:35 REDACTED sh[923486]:     at file:///usr/lib/meerkat/main.js:104858:29
Dec 25 16:12:35 REDACTED sh[923486]:     at Array.map (<anonymous>)
Dec 25 16:12:35 REDACTED sh[923486]:     at file:///usr/lib/meerkat/main.js:104857:44
Dec 25 16:12:35 REDACTED sh[923486]: Node.js v20.19.6
```

This is solely because of the `transfer` function not being defined until NodeJS version 21.x.x. The newest Debian stable version (and therefore on Ubuntu) is 20.19.1. So I can either delay this package until a higher version of NodeJS lands in Ubuntu (which might not be the next release in April), or I could just modify `pem-ts` to not use this dependency, and then Meerkat DSA _might_ work on 20.19.1 as is. NodeJS 20.19.1 [is compatible with Prisma](https://www.prisma.io/docs/orm/more/upgrade-guides/upgrading-versions/upgrading-to-prisma-7), I don't think there is a compatibility problem with any other dependency.

My plan tomorrow is to remove `@std/encoding` as a dependency of `pem-ts` and just embed the Base64 code in the package. It would make it zero-dependencies, and it should work on older versions of NodeJS.

**Comment by JonathanWilbur** [comment]
I now have Meerkat DSA installing locally, running migrations, and starting up successfully on Ubuntu. Now what remains to be done (inclusively):

- [ ] `prisma` is not executable
- [ ] Reintroduce `ProtectSystem=strict`
- [ ] Make `/usr/lib` owned by root
- [ ] Correct uninstallation / purge

**Comment by JonathanWilbur** [comment]
A separate PR will be needed to build Debian packages and sign them with cosign.
